version: '1.0'

services:
  # Front-end service (e.g., React, Angular, etc.)
  front-end:
    build:
      context: ./front-end  # Path to the front-end Dockerfile
      dockerfile: Dockerfile # Optional: only needed if the Dockerfile has a different name
    container_name: front-end
    ports:
      - "4173:4173"  # Adjust port as needed
    depends_on:
      - back-end
 
  # Back-end service (e.g., Node.js, Python, etc.)
  back-end:
    build:
      context: ./back-end  # Path to the back-end Dockerfile
      dockerfile: Dockerfile # Optional: only needed if the Dockerfile has a different name
    container_name: back-end
    ports:
      - "5000:5000"  # Adjust port as needed
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
